spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ixmyyrdmgxrgvurnvtqm
spring.datasource.password=9842315131@RK
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update database tables based on Java models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port for Backend Server
server.port=8080
